### ISSUE TITLE
Jobson-UI success story

### ISSUE THREAD

**Issue by ghost** [adamkewley/jobson#104]
Thanks to Jobson-UI frontend, i am able to run a simple AI Image Upscaler commercially here: https://artificigenix.com

![image](https://user-images.githubusercontent.com/46110534/197945277-732ad19b-5b79-4935-a23b-759975785a99.png)

**Comment by adamkewley** [comment]
Oh, wow!

Thank you very much for posting this: it always makes me happy when I see someone succeed in actually using jobson :D - I hope the best for your project!

**Comment by adamkewley** [comment]
Thanks for this, I'll close this out! It was a nice gesture!
