### ISSUE TITLE
Feature request: Allow path type argument.

### ISSUE THREAD

**Issue by ripley** [adamkewley/jobson#115]
e.g.:
`my_command --arg1 /path/to/file_1.csv --arg2 /path/to/file_2.yaml`
Some time I need to ask a command line tool to process local file.
It'll be nice if this is supported.

**Comment by adamkewley** [comment]
Closing this,

Thanks for the input, but the project has has a `Jobson is effectively unmaintained` notice for 10 months now, and has had no further changes since then, so I am closing all issues and archiving the project until further notice.
