### ISSUE TITLE
Add event hooks support

### ISSUE THREAD

**Issue by adamkewley** [adamkewley/jobson#23]
Stub for wider implementation. 

Overall:

- Add support for a `hooks/` dir in a Jobson workspace
- The `hooks/` dir MAY exist and MAY contain an executable file named by the event (e.g. `after-job-complete`)
- The `jobson` server executes the hook script at relevant times. The exit code of the hook MAY be relevant to the overall execution pipeline (e.g. if `before-job-submission` hook exits with nonzero, do not allow job to be submitted)

This feature enables Jobson to be extended with dynamic events, such as sending an email when a job completes.

**Comment by mtazzari** [comment]
This would be a cool feature. It would allow, e.g., to implement a callback functionality.
For example, it would allow to avoid implementing websockets into a webapp to have updated information on the jobs status.

**Comment by adamkewley** [comment]
This feature has been kicked into the `1.x` wishlist: it's a valuable feature but will be re-opened once actual development begins on it (it's stale as-is here). The feature will not be in `1.0.0`.
