### ISSUE TITLE
Unable to remove jobs from jobson UI

### ISSUE THREAD

**Issue by mtazzari** [adamkewley/jobson#54]
It would be handy to be able to delete/remove a job from jobson UI.
Use case: 

1) An application submits a request to jobson. It gets assigned a `jobID`.
2) If the job finishes correctly, the application fetches the outputs in `jobs/jobID/outputs` and removes the `jobs/jobID` directory to cleanup space. If the job fails, the application doesn't remove the `jobs/jobID` directory as it contains `stdout` and `stderr` that can be viewed from jobson UI and provide useful information for debugging.
3) After a bugfix, the application submits a new job to jobson. The job succeeds and therefore the application takes the outputs and removes the directory of this new successful job.
The job that failed remains dangling both and leaves `wds/jobID` and in the `jobs/jobID` directories.

It would be really useful to have a "remove" button in jobson UI (e.g. next to "copy" and "view") so that a manual intervention via terminal is not required to clean the jobson directory.

**Comment by adamkewley** [comment]
@mtazzari thanks for this, I'll try and get this added for you asap but I'm currently very busy. 

I began implementing it tonight on a side branch:

https://github.com/adamkewley/jobson/tree/feature-delete-job

But, as with any new feature, I need to write the relevant unit + systemtests + documentation as I go along so, although the code is quite easy, it will take another session to thrash out. Also, I recall there are some issues with having the server delete data: a deployment I'm running uses an NFS to store the data and, IIRC, recursively deleting an active dir from NFS can sometimes leave remnants behind that confuse the server.

Current commit for this 5a11406a8c

**Comment by adamkewley** [comment]
The server-side requirements for this were implemented in 1.0.1:

https://github.com/adamkewley/jobson/releases/tag/1.0.1

Which means jobs can be deleted via the HTTP API (e.g. with curl, python scripts, etc.).

Adding it to the UI is the next phase, but it might be necessary to handle authorization to implement this. The reason why is that, without authorization, users can easily delete other users jobs.

**Comment by adamkewley** [comment]
Closing this for now - the API additions were made but there was no follow up (or use complains). I'm guessing @mtazzari has moved onto more feature-filled pastures (I wouldn't blame him - I only get an hour or two here or there to maintain this).
