### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by NicoHood** [adamkewley/jobson#84]
Hi,
the demo page linked in the readme is currently offline. Is this project still actively maintained?

**Comment by adamkewley** [comment]
@NicoHood , server's down atm because I skipped a few payments :->. I might try and get it back up but it will take time

It's only semi-maintained. I occasionally patch it up with the latest libraries etc. but it isn't under active full-time development.

**Comment by adamkewley** [comment]
@NicoHood , as a follow-up to this, I've got the server back up and a demo is now hosted at https://jobson.adamkewley.com . The README was also updated with the new (cleaner) link. Thank you for pointing this out! :)
