### ISSUE TITLE
Paths do not match in jobson-ui demo

### ISSUE THREAD

**Issue by aruth-perovskite** [adamkewley/jobson#86]
In the demo located here: https://adamkewley.github.io/jobson/ui.html

There is a step to copy the jobson-ui assets using the following command:

> cp -r /usr/share/jobson/ui/html /var/www/jobson

In the nginx server configuration the root directory is specified as:

> root /var/www/jobson-ui;

These directories do not match and result in a 404 not found error. The directories should be made to match.

**Comment by adamkewley** [comment]
Thanks for this. I'll fix the typo when I get a spare 30 min (my Jobson dev environment was recently nuked) and mention this issue in the commit.
