### ISSUE TITLE
https://crisprcastyper.crispr.dk service isn't working

### ISSUE THREAD

**Issue by ellinium** [adamkewley/jobson#91]
Hi,
I've tried your online webservice, but it seems like it stopped working, tried 3 jobs, never got the results.
It definitely was working last year.

**Comment by adamkewley** [comment]
@ellinium I do not host that service. It's hosted by a third-party, who may be performing maintenance (or enountering a bug in Jobson ;)).

This repository is for (some of) the source code that backs that service. If there's a bug in Jobson, here's the place to report it. If there's a bug with the service, it should be reported to the provider (@Russel88 , I think). The service provider can then check whether it's a problem on their side or a problem in Jobson.

**Comment by Russel88** [comment]
@ellinium https://crisprcastyper.crispr.dk should be up and running again.
If you experience problems in the future please post them here: https://github.com/Russel88/CRISPRCasTyper

**Comment by ellinium** [comment]
all good, thank you!
